const signature = 'sha256=6230d46f98da5d647b625b61c01d7ae41cc346f02165edd8d873cf7c44d5d1bc';


const payload = {
    "zen": "Encourage flow.",
    "hook_id": 399091207,
    "hook": {
        "type": "Repository",
        "id": 399091207,
        "name": "web",
        "active": true,
        "events": [
            "push"
        ],
        "config": {
            "content_type": "json",
            "insecure_ssl": "0",
            "secret": "********",
            "url": "http://45.7.231.143/"
        },
        "updated_at": "2023-01-31T12:40:50Z",
        "created_at": "2023-01-31T12:40:50Z",
        "url": "https://api.github.com/repos/matiasguzlop/whdeployer/hooks/399091207",
        "test_url": "https://api.github.com/repos/matiasguzlop/whdeployer/hooks/399091207/test",
        "ping_url": "https://api.github.com/repos/matiasguzlop/whdeployer/hooks/399091207/pings",
        "deliveries_url": "https://api.github.com/repos/matiasguzlop/whdeployer/hooks/399091207/deliveries",
        "last_response": {
            "code": null,
            "status": "unused",
            "message": null
        }
    },
    "repository": {
        "id": 595579998,
        "node_id": "R_kgDOI3_UXg",
        "name": "whdeployer",
        "full_name": "matiasguzlop/whdeployer",
        "private": true,
        "owner": {
            "login": "matiasguzlop",
            "id": 51770264,
            "node_id": "MDQ6VXNlcjUxNzcwMjY0",
            "avatar_url": "https://avatars.githubusercontent.com/u/51770264?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/matiasguzlop",
            "html_url": "https://github.com/matiasguzlop",
            "followers_url": "https://api.github.com/users/matiasguzlop/followers",
            "following_url": "https://api.github.com/users/matiasguzlop/following{/other_user}",
            "gists_url": "https://api.github.com/users/matiasguzlop/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/matiasguzlop/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/matiasguzlop/subscriptions",
            "organizations_url": "https://api.github.com/users/matiasguzlop/orgs",
            "repos_url": "https://api.github.com/users/matiasguzlop/repos",
            "events_url": "https://api.github.com/users/matiasguzlop/events{/privacy}",
            "received_events_url": "https://api.github.com/users/matiasguzlop/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/matiasguzlop/whdeployer",
        "description": "A server to deploy things using GitHub Webhooks.",
        "fork": false,
        "url": "https://api.github.com/repos/matiasguzlop/whdeployer",
        "forks_url": "https://api.github.com/repos/matiasguzlop/whdeployer/forks",
        "keys_url": "https://api.github.com/repos/matiasguzlop/whdeployer/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/matiasguzlop/whdeployer/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/matiasguzlop/whdeployer/teams",
        "hooks_url": "https://api.github.com/repos/matiasguzlop/whdeployer/hooks",
        "issue_events_url": "https://api.github.com/repos/matiasguzlop/whdeployer/issues/events{/number}",
        "events_url": "https://api.github.com/repos/matiasguzlop/whdeployer/events",
        "assignees_url": "https://api.github.com/repos/matiasguzlop/whdeployer/assignees{/user}",
        "branches_url": "https://api.github.com/repos/matiasguzlop/whdeployer/branches{/branch}",
        "tags_url": "https://api.github.com/repos/matiasguzlop/whdeployer/tags",
        "blobs_url": "https://api.github.com/repos/matiasguzlop/whdeployer/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/matiasguzlop/whdeployer/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/matiasguzlop/whdeployer/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/matiasguzlop/whdeployer/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/matiasguzlop/whdeployer/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/matiasguzlop/whdeployer/languages",
        "stargazers_url": "https://api.github.com/repos/matiasguzlop/whdeployer/stargazers",
        "contributors_url": "https://api.github.com/repos/matiasguzlop/whdeployer/contributors",
        "subscribers_url": "https://api.github.com/repos/matiasguzlop/whdeployer/subscribers",
        "subscription_url": "https://api.github.com/repos/matiasguzlop/whdeployer/subscription",
        "commits_url": "https://api.github.com/repos/matiasguzlop/whdeployer/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/matiasguzlop/whdeployer/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/matiasguzlop/whdeployer/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/matiasguzlop/whdeployer/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/matiasguzlop/whdeployer/contents/{+path}",
        "compare_url": "https://api.github.com/repos/matiasguzlop/whdeployer/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/matiasguzlop/whdeployer/merges",
        "archive_url": "https://api.github.com/repos/matiasguzlop/whdeployer/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/matiasguzlop/whdeployer/downloads",
        "issues_url": "https://api.github.com/repos/matiasguzlop/whdeployer/issues{/number}",
        "pulls_url": "https://api.github.com/repos/matiasguzlop/whdeployer/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/matiasguzlop/whdeployer/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/matiasguzlop/whdeployer/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/matiasguzlop/whdeployer/labels{/name}",
        "releases_url": "https://api.github.com/repos/matiasguzlop/whdeployer/releases{/id}",
        "deployments_url": "https://api.github.com/repos/matiasguzlop/whdeployer/deployments",
        "created_at": "2023-01-31T11:32:20Z",
        "updated_at": "2023-01-31T12:34:38Z",
        "pushed_at": "2023-01-31T12:34:34Z",
        "git_url": "git://github.com/matiasguzlop/whdeployer.git",
        "ssh_url": "git@github.com:matiasguzlop/whdeployer.git",
        "clone_url": "https://github.com/matiasguzlop/whdeployer.git",
        "svn_url": "https://github.com/matiasguzlop/whdeployer",
        "homepage": null,
        "size": 1,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "private",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main"
    },
    "sender": {
        "login": "matiasguzlop",
        "id": 51770264,
        "node_id": "MDQ6VXNlcjUxNzcwMjY0",
        "avatar_url": "https://avatars.githubusercontent.com/u/51770264?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/matiasguzlop",
        "html_url": "https://github.com/matiasguzlop",
        "followers_url": "https://api.github.com/users/matiasguzlop/followers",
        "following_url": "https://api.github.com/users/matiasguzlop/following{/other_user}",
        "gists_url": "https://api.github.com/users/matiasguzlop/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/matiasguzlop/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/matiasguzlop/subscriptions",
        "organizations_url": "https://api.github.com/users/matiasguzlop/orgs",
        "repos_url": "https://api.github.com/users/matiasguzlop/repos",
        "events_url": "https://api.github.com/users/matiasguzlop/events{/privacy}",
        "received_events_url": "https://api.github.com/users/matiasguzlop/received_events",
        "type": "User",
        "site_admin": false
    }
};

module.exports = {
    signature,
    payload
};